# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' << user.email
# Environment variables (ENV['...']) can be set in the file config/application.yml.
# See http://railsapps.github.io/rails-environment-variables.html


Country.delete_all
china = Country.create( name: "China" )
us = Country.create( name: "United States" )

china_province = [
  "Anhui",
  "Beijing",
  "Chongqing",
  "Fujian",
  "Gansu",
  "Guangdong",
  "Guangxi",
  "Guizhou",
  "Hainan",
  "Hebei",
  "Heilongjiang",
  "Henan",
  "Hong Kong",
  "Hubei",
  "Hunan",
  "Inner Mongolia",
  "Jiangsu",
  "Jiangxi",
  "Jilin",
  "Liaoning",
  "Macau",
  "Ningxia",
  "Qinghai",
  "Shaanxi",
  "Shandong",
  "Shanghai",
  "Shanxi",
  "Sichuan",
  "Tibet",
  "Tianjin",
  "Xinjiang",
  "Yunnan",
  "Zhejiang"
]

us_province = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming"
]

Province.delete_all
china_province.each do |name|
  Province.create( name: name, country: china )
end

us_province.each do |name|
  Province.create( name: name, country: us )
end

study_field = [
  "Accounting",
  "Acting",
  "Advertising",
  "Air Force ROTC",
  "Army ROTC",
  "Alternative Dispute Resolution",
  "Anthropology",
  "Applied Arts and Sciences",
  "Applied Behavior Analysis",
  "Applied Technology and Performance Improvement",
  "Archaeology",
  "Art History",
  "Athletics",
  "Aviation Logistics",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Integrated Studies",
  "Campus Life",
  "Career Services",
  "Ceramics",
  "Chemistry",
  "Communication Design",
  "Communication Studies",
  "Composition (College of Music)",
  "Computer Engineering",
  "Computer Science",
  "Construction Engineering Technology",
  "Converged Broadcast Media",
  "Credit by Examination",
  "Criminal Justice",
  "Cultural Programs and Services",
  "Dance",
  "Decision Sciences",
  "Dentistry",
  "Development and Family Studies",
  "Digital Retailing",
  "Disability Accommodation",
  "Drawing and Painting",
  "Ecology for Environmental Science",
  "Economics (College of Arts & Sciences)",
  "Economics (College of Business)",
  "Electrical Engineering",
  "Electrical Engineering Technology",
  "Elementary, Middle School and Secondary Education",
  "Emergency Administration and Planning",
  "Engineering",
  "English",
  "Entrepreneurship",
  "Fashion Design",
  "Fibers",
  "Film",
  "Finance",
  "Financial Services",
  "Fitness & rec sports",
  "Forensic Science",
  "Fraternities and sororities",
  "French",
  "Geography",
  "Geology",
  "German",
  "Health Promotion",
  "Health-Related Preprofessional Programs",
  "History",
  "Home Furnishings Merchandising",
  "Honors College",
  "Hospitality Management",
  "Information Science",
  "Information Systems",
  "Information Technology",
  "Instrumental Performance",
  "Insurance",
  "Integrative Studies",
  "Interdisciplinary Art and Design Studies",
  "Interior Design",
  "International Studies",
  "Internships",
  "Jazz Studies",
  "Journalism",
  "Keyboard Performance",
  "Kinesiology (Physical Education)",
  "Leadership, Mentoring and Study Skills",
  "LGBT Studies",
  "Logistics and Supply Chain Management",
  "Linguistics",
  "Marketing",
  "Materials Science and Engineering",
  "Mathematics",
  "Mechanical and Energy Engineering",
  "Mechanical Engineering Technology",
  "Medicine",
  "Medical Laboratory Sciences",
  "Merchandising",
  "Metalsmithing and Jewelry",
  "Music (Bachelor of Arts program)",
  "Music Education",
  "Music Theory",
  "National Student Exchange",
  "New Media Art",
  "News Writing",
  "Operations and Supply Chain Management ",
  "Organizational Behavior and Human Resource Management",
  "Philosophy",
  "Photography",
  "Photojournalism",
  "Physical Therapy",
  "Physics",
  "Political Science",
  "Pre-Law information",
  "Printmaking",
  "Professional and Technical Communication",
  "Public Relations",
  "Psychology",
  "Radio, Television and Film",
  "Real Estate",
  "Recreation, Event and Sport Management",
  "Rehabilitation Studies",
  "Religious Studies",
  "Risk, Insurance and Financial Services",
  "Sculpture",
  "Seminary",
  "Social Science",
  "Social Work",
  "Sociology",
  "Spanish",
  "Speech-Language Pathology/Audiology",
  "Student Employment",
  "Study Abroad",
  "Teacher Certification Programs",
  "Television",
  "Texas Academy of Mathematics & Science",
  "Theatre",
  "Veterinary",
  "Visual Arts and Design",
  "Visual Art Studies (teacher preparation)",
  "Vocal Performance",
  "Women's and Gender Studies",
  "World Languages, Literatures and Cultures"
]

StudyField.delete_all
study_field.each do |name|
  StudyField.create( name: name )
end